'use client'

import { useState, useCallback, useEffect, useRef } from 'react'
import JSZip from 'jszip'

interface CodeViewModalProps {
  code: string
  fileName?: string
  appName?: string
  onClose: () => void
}

function formatBytes(bytes: number): string {
  if (bytes < 1024) return `${bytes} B`
  return `${(bytes / 1024).toFixed(1)} KB`
}

// ─── ZIP 내부 파일 템플릿 ──────────────────────────────────────────────────────

function toPackageName(appName: string): string {
  return (
    appName
      .toLowerCase()
      .trim()
      .replace(/\s+/g, '-')
      .replace(/[^a-z0-9-]/g, '')
      .replace(/^-+|-+$/g, '') || 'generated-app'
  )
}

function makePackageJson(packageName: string): string {
  return JSON.stringify(
    {
      name: packageName,
      version: '0.1.0',
      private: true,
      scripts: { dev: 'next dev', build: 'next build', start: 'next start' },
      dependencies: { next: '^15.0.0', react: '^19.0.0', 'react-dom': '^19.0.0' },
      devDependencies: {
        typescript: '^5',
        '@types/node': '^20',
        '@types/react': '^19',
        '@types/react-dom': '^19',
      },
    },
    null,
    2
  )
}

const TSCONFIG_JSON = JSON.stringify(
  {
    compilerOptions: {
      target: 'ES2017',
      lib: ['dom', 'dom.iterable', 'esnext'],
      allowJs: true,
      skipLibCheck: true,
      strict: true,
      noEmit: true,
      esModuleInterop: true,
      module: 'esnext',
      moduleResolution: 'bundler',
      resolveJsonModule: true,
      isolatedModules: true,
      jsx: 'preserve',
      incremental: true,
      plugins: [{ name: 'next' }],
      paths: { '@/*': ['./src/*'] },
    },
    include: ['next-env.d.ts', '**/*.ts', '**/*.tsx', '.next/types/**/*.ts'],
    exclude: ['node_modules'],
  },
  null,
  2
)

const NEXT_CONFIG = `import type { NextConfig } from 'next'

const nextConfig: NextConfig = {}

export default nextConfig
`

const GITIGNORE = `node_modules/
.next/
out/
.env*.local
`

function makeReadme(appName: string): string {
  return `# ${appName}

[MyWebAppBuilder](https://my-web-app-builder.vercel.app)로 생성된 Next.js 앱입니다.

## 시작하기

\`\`\`bash
npm install
npm run dev
\`\`\`

브라우저에서 http://localhost:3000 을 열면 앱을 확인할 수 있습니다.

## 구조

\`\`\`
src/
└── app/
    ├── layout.tsx
    ├── page.tsx
    ├── globals.css
    └── components/
        └── GeneratedApp.tsx   ← 생성된 컴포넌트
\`\`\`

## 현재 한계

이 앱은 UI 프로토타입입니다. 아래 기능은 포함되지 않습니다.

- **데이터베이스**: 모든 데이터는 코드에 하드코딩된 초기값입니다.
- **로그인 / 인증**: 사용자 계정 기능이 없습니다.
- **서버 API**: 외부 서버와 통신하지 않습니다.
- **이미지 업로드**: 파일 첨부 기능이 없습니다.
- **버튼 / 폼 동작**: 클릭 시 브라우저 알림(alert)으로 대체됩니다.
- **채팅 메시지**: 브라우저 내부 상태만 변경되며 서버로 전송되지 않습니다.

## 커스터마이즈

\`src/app/components/GeneratedApp.tsx\`를 직접 수정해 기능을 추가할 수 있습니다.
`
}

const LAYOUT_TSX = `import type { Metadata } from 'next'
import './globals.css'

export const metadata: Metadata = {
  title: 'Generated App',
  description: 'Generated by MyWebAppBuilder',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="ko">
      <body>{children}</body>
    </html>
  )
}
`

const PAGE_TSX = `import GeneratedApp from './components/GeneratedApp'

export default function Page() {
  return <GeneratedApp />
}
`

const GLOBALS_CSS = `*, *::before, *::after {
  box-sizing: border-box;
  margin: 0;
  padding: 0;
}

body {
  font-family: system-ui, sans-serif;
}
`

export default function CodeViewModal({
  code,
  fileName = 'generated-app.tsx',
  appName = 'Generated App',
  onClose,
}: CodeViewModalProps) {
  const [copied, setCopied] = useState(false)
  const [inlineCopied, setInlineCopied] = useState(false)
  const [zipping, setZipping] = useState(false)
  const codeRef = useRef<HTMLPreElement>(null)

  const lineCount = code.split('\n').length
  const byteSize = formatBytes(new TextEncoder().encode(code).length)

  useEffect(() => {
    const onKey = (e: KeyboardEvent) => {
      if (e.key === 'Escape') onClose()
    }
    window.addEventListener('keydown', onKey)
    return () => window.removeEventListener('keydown', onKey)
  }, [onClose])

  const copyCode = useCallback(async () => {
    try {
      await navigator.clipboard.writeText(code)
      return true
    } catch {
      return false
    }
  }, [code])

  const handleFooterCopy = useCallback(async () => {
    const ok = await copyCode()
    if (!ok) return
    setCopied(true)
    setTimeout(() => setCopied(false), 2000)
  }, [copyCode])

  const handleInlineCopy = useCallback(async () => {
    const ok = await copyCode()
    if (!ok) return
    setInlineCopied(true)
    setTimeout(() => setInlineCopied(false), 2000)
  }, [copyCode])

  const handleDownload = useCallback(() => {
    const blob = new Blob([code], { type: 'text/plain;charset=utf-8' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = fileName
    document.body.appendChild(a)
    a.click()
    document.body.removeChild(a)
    URL.revokeObjectURL(url)
  }, [code, fileName])

  const handleDownloadZip = useCallback(async () => {
    setZipping(true)
    const packageName = toPackageName(appName)
    try {
      const zip = new JSZip()
      zip.file('package.json', makePackageJson(packageName))
      zip.file('tsconfig.json', TSCONFIG_JSON)
      zip.file('next.config.ts', NEXT_CONFIG)
      zip.file('.gitignore', GITIGNORE)
      zip.file('README.md', makeReadme(appName))
      zip.file('src/app/layout.tsx', LAYOUT_TSX)
      zip.file('src/app/page.tsx', PAGE_TSX)
      zip.file('src/app/globals.css', GLOBALS_CSS)
      zip.file('src/app/components/GeneratedApp.tsx', code)

      const blob = await zip.generateAsync({ type: 'blob', compression: 'DEFLATE' })
      const url = URL.createObjectURL(blob)
      const a = document.createElement('a')
      a.href = url
      a.download = `${packageName}.zip`
      document.body.appendChild(a)
      a.click()
      document.body.removeChild(a)
      URL.revokeObjectURL(url)
    } finally {
      setZipping(false)
    }
  }, [code, appName])

  return (
    <div
      className="fixed inset-0 z-50 flex items-end sm:items-center justify-center bg-black/60 p-0 sm:p-4"
      onClick={onClose}
    >
      <div
        className="bg-white w-full sm:max-w-2xl sm:rounded-2xl shadow-2xl flex flex-col"
        style={{ maxHeight: '90vh' }}
        onClick={(e) => e.stopPropagation()}
      >
        {/* Header */}
        <div className="flex items-center justify-between px-5 py-4 border-b border-gray-100 shrink-0">
          <div>
            <h2 className="text-sm font-semibold text-gray-900">생성된 코드</h2>
            <p className="text-xs text-gray-400 mt-0.5">
              React TSX · {lineCount}줄 · {byteSize}
            </p>
          </div>
          <button
            onClick={onClose}
            className="w-8 h-8 flex items-center justify-center rounded-full text-gray-400 hover:text-gray-600 hover:bg-gray-100 transition-colors text-lg leading-none"
            aria-label="닫기"
          >
            ×
          </button>
        </div>

        {/* Usage info banner */}
        <div className="px-5 py-3 bg-blue-50 border-b border-blue-100 shrink-0 flex items-start gap-2.5">
          <svg
            width="15"
            height="15"
            viewBox="0 0 15 15"
            fill="none"
            aria-hidden="true"
            className="text-blue-500 mt-0.5 shrink-0"
          >
            <circle cx="7.5" cy="7.5" r="6.5" stroke="currentColor" strokeWidth="1.3" />
            <path
              d="M7.5 6.5v5M7.5 4.5v.5"
              stroke="currentColor"
              strokeWidth="1.5"
              strokeLinecap="round"
            />
          </svg>
          <div className="text-xs text-blue-800 leading-relaxed">
            <p className="font-semibold mb-1">이 파일은 단독으로 실행할 수 없습니다</p>
            <p>
              <code className="font-mono bg-blue-100 px-1 rounded">react</code>,{' '}
              <code className="font-mono bg-blue-100 px-1 rounded">typescript</code> 의존성이 있는
              프로젝트 안에 넣어야 정상 인식됩니다.
            </p>
            <p className="mt-1">
              예시 경로:{' '}
              <code className="font-mono bg-blue-100 px-1 rounded">
                src/components/GeneratedApp.tsx
              </code>
            </p>
            <p className="mt-1 text-blue-600 font-medium">
              ZIP 다운로드로 바로 실행 가능한 Next.js 프로젝트를 받을 수 있습니다.
            </p>
          </div>
        </div>

        {/* Code block */}
        <div className="relative flex-1 min-h-0 overflow-y-auto bg-gray-950 group">
          {/* Inline copy button — visible on hover */}
          <button
            onClick={handleInlineCopy}
            title="코드 복사"
            className={`absolute top-3 right-3 z-10 flex items-center gap-1.5 px-2.5 py-1.5 rounded-md text-xs font-medium transition-all duration-200 opacity-0 group-hover:opacity-100 focus:opacity-100 ${
              inlineCopied
                ? 'bg-green-600 text-white'
                : 'bg-gray-700 text-gray-300 hover:bg-gray-600 hover:text-white'
            }`}
          >
            {inlineCopied ? (
              <>
                <svg width="12" height="12" viewBox="0 0 12 12" fill="none" aria-hidden="true">
                  <path
                    d="M1.5 6l3 3 6-6"
                    stroke="currentColor"
                    strokeWidth="1.8"
                    strokeLinecap="round"
                    strokeLinejoin="round"
                  />
                </svg>
                복사됨
              </>
            ) : (
              <>
                <svg width="12" height="12" viewBox="0 0 12 12" fill="none" aria-hidden="true">
                  <rect
                    x="3.5"
                    y="0.5"
                    width="8"
                    height="9"
                    rx="1.5"
                    stroke="currentColor"
                    strokeWidth="1.2"
                  />
                  <path
                    d="M0.5 3.5h2.5v8a1 1 0 001 1h6"
                    stroke="currentColor"
                    strokeWidth="1.2"
                    strokeLinecap="round"
                  />
                </svg>
                복사
              </>
            )}
          </button>

          <pre
            ref={codeRef}
            className="p-5 text-[11px] sm:text-xs text-gray-100 leading-relaxed font-mono whitespace-pre overflow-x-auto"
          >
            <code>{code}</code>
          </pre>
        </div>

        {/* Footer */}
        <div className="flex items-center justify-between gap-2 px-5 py-3 border-t border-gray-100 shrink-0">
          {/* Left: download buttons */}
          <div className="flex items-center gap-2">
            <button
              onClick={handleDownload}
              title={`${fileName} 파일로 다운로드`}
              className="flex items-center gap-1.5 px-3 py-2 rounded-lg text-xs font-medium transition-colors border border-gray-200 bg-white text-gray-600 hover:bg-gray-50 hover:border-gray-300"
            >
              <svg width="13" height="13" viewBox="0 0 14 14" fill="none" aria-hidden="true">
                <path
                  d="M7 1v8M4 6l3 3 3-3M2 11h10"
                  stroke="currentColor"
                  strokeWidth="1.5"
                  strokeLinecap="round"
                  strokeLinejoin="round"
                />
              </svg>
              .tsx
            </button>
            <button
              onClick={handleDownloadZip}
              disabled={zipping}
              title="Next.js 프로젝트 ZIP 다운로드"
              className="flex items-center gap-1.5 px-3 py-2 rounded-lg text-xs font-medium transition-colors border border-indigo-200 bg-indigo-50 text-indigo-700 hover:bg-indigo-100 hover:border-indigo-300 disabled:opacity-60 disabled:cursor-not-allowed"
            >
              {zipping ? (
                <>
                  <svg
                    width="13"
                    height="13"
                    viewBox="0 0 14 14"
                    fill="none"
                    aria-hidden="true"
                    className="animate-spin"
                  >
                    <circle
                      cx="7"
                      cy="7"
                      r="5.5"
                      stroke="currentColor"
                      strokeWidth="1.5"
                      strokeDasharray="20 14"
                    />
                  </svg>
                  생성 중…
                </>
              ) : (
                <>
                  <svg width="13" height="13" viewBox="0 0 14 14" fill="none" aria-hidden="true">
                    <rect
                      x="1"
                      y="1"
                      width="12"
                      height="12"
                      rx="2"
                      stroke="currentColor"
                      strokeWidth="1.3"
                    />
                    <path
                      d="M5 1v4h4V1M7 8v3M5.5 9.5l1.5 1.5 1.5-1.5"
                      stroke="currentColor"
                      strokeWidth="1.3"
                      strokeLinecap="round"
                      strokeLinejoin="round"
                    />
                  </svg>
                  ZIP 다운로드
                </>
              )}
            </button>
          </div>

          {/* Right: copy button */}
          <button
            onClick={handleFooterCopy}
            title="전체 코드를 클립보드에 복사"
            className={`flex items-center gap-2 px-4 py-2 rounded-lg text-sm font-medium transition-colors ${
              copied ? 'bg-green-500 text-white' : 'bg-gray-900 text-white hover:bg-gray-700'
            }`}
          >
            {copied ? (
              <>
                <svg width="14" height="14" viewBox="0 0 14 14" fill="none" aria-hidden="true">
                  <path
                    d="M2 7l4 4 6-7"
                    stroke="currentColor"
                    strokeWidth="2"
                    strokeLinecap="round"
                    strokeLinejoin="round"
                  />
                </svg>
                복사됨!
              </>
            ) : (
              <>
                <svg width="14" height="14" viewBox="0 0 14 14" fill="none" aria-hidden="true">
                  <rect
                    x="4"
                    y="1"
                    width="9"
                    height="10"
                    rx="1.5"
                    stroke="currentColor"
                    strokeWidth="1.5"
                  />
                  <path
                    d="M1 4h2m0 0v8a1 1 0 001 1h7"
                    stroke="currentColor"
                    strokeWidth="1.5"
                    strokeLinecap="round"
                  />
                </svg>
                복사하기
              </>
            )}
          </button>
        </div>
      </div>
    </div>
  )
}
